export const ROUTES = {
  MAIN: '/',
  HOME: '/home',
  CHARACTER: '/character',
  CHARACTER_ERROR: '/character/error',
  ANALYZE: '/analyze',
  RESULT: '/result',
  INSTALL_GUIDE: '/install-guide',
  MYPAGE: '/mypage',
  LOGIN: '/login',
  SIGNUP: '/signup',
  NICKNAME: '/signup/nickname',
  BOOK_DETAIL: '/book/:id',
  MEMO_EDIT: '/memo-edit',
  SHOP: '/shop',
  CHAT: '/chat',
  SEARCH: '/search',
}
